--TIPOS DE USUARIO 
INSERT INTO TIPO_USUARIOS (ID_TIPO, DESCRIPCION_USUARIO, DIAS_PRESTAMO) VALUES (1, 'AFILIADO', 10);
INSERT INTO TIPO_USUARIOS (ID_TIPO, DESCRIPCION_USUARIO, DIAS_PRESTAMO) VALUES (2, 'EMPLEADO', 8);
INSERT INTO TIPO_USUARIOS (ID_TIPO, DESCRIPCION_USUARIO, DIAS_PRESTAMO) VALUES (3, 'INVITADO', 7);

--LIBROS
INSERT INTO LIBROS (ID_LIBRO, ANIO_LIBRO, AUTOR_LIBRO, ISBN_LIBRO, TITULO_LIBRO) VALUES (1, 1524, 'CEIBA', 'DASD154212', 'TEST LIBRO 1');
INSERT INTO LIBROS (ID_LIBRO, ANIO_LIBRO, AUTOR_LIBRO, ISBN_LIBRO, TITULO_LIBRO) VALUES (2, 1974, 'CEIBA', 'F8D7S5D4SD', 'TEST LIBRO 2');
INSERT INTO LIBROS (ID_LIBRO, ANIO_LIBRO, AUTOR_LIBRO, ISBN_LIBRO, TITULO_LIBRO) VALUES (3, 2001, 'CEIBA', '4ADSA4AD4S', 'TEST LIBRO 3');
INSERT INTO LIBROS (ID_LIBRO, ANIO_LIBRO, AUTOR_LIBRO, ISBN_LIBRO, TITULO_LIBRO) VALUES (4, 2020, 'CEIBA', 'S8D7S5D4FS', 'TEST LIBRO 4');


--USUARIOS
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE_USUARIO, NROIDENTIFICACION_USUARIO, ID_TIPO) VALUES (1, 'EDUAR', '57S5D7SD78', 1);
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE_USUARIO, NROIDENTIFICACION_USUARIO, ID_TIPO) VALUES (2, 'DANILO', 'DF74ED65B1', 2);
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE_USUARIO, NROIDENTIFICACION_USUARIO, ID_TIPO) VALUES (3, 'LUIS', 'L7412WS71N', 3);